# Auto-generated by `nix run .#write-recipients` - DO NOT EDIT MANUALLY
# Derived dynamically from identities.nix
{
  recipients = {
    ixo = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPobJWkfYiOfQ/dfIz6HYY9LooERxuxXBQGE+oBxQpPH";
    ixo-tpm = "age1tpm1qt0wrxgpsmxq6s29wydwrc4hedg3mpn6utl5e8adrnmau5f4udghvs66e5k";
    portable-yubikey = "age1yubikey1qd5rn4s8d04pjkhqe4xq8nspc883gm7jnnk3pucsr33yg6eq00v9uq5tsas";
  };
}
