{ inputs, ... }:
let
  identitiesData = import ../../secrets/identities.nix;
  identitiesText = builtins.concatStringsSep "\n\n" (builtins.attrValues identitiesData.identities);

  secretPackages = pkgs: system: [
    pkgs.rage
    pkgs.ssh-to-age
    pkgs.age-plugin-tpm
    pkgs.age-plugin-yubikey
    inputs.ragenix.packages.${system}.default
    # TODO: Replace pass with something like passage (or a better alternative) eventually
    pkgs.pass
  ];
in
{
  flake-file.inputs.ragenix = {
    url = "github:yaxitech/ragenix";
    inputs = {
      nixpkgs.follows = "nixpkgs";
      agenix.inputs.home-manager.follows = "home-manager";
    };
  };

  perSystem =
    { pkgs, system, ... }:
    {
      devshells.default = {
        devshell.packages = secretPackages pkgs system;
      };

      apps.write-recipients = {
        type = "app";
        program =
          let
            script = pkgs.writeShellScriptBin "write-recipients" ''
              set -euo pipefail
              ROOT_DIR="$(git rev-parse --show-toplevel)"
              RECIPIENTS_FILE="$ROOT_DIR/secrets/recipients.nix"

              echo "Dynamically deriving recipients from secrets/identities.nix..."

              # Evaluate secrets/identities.nix dynamically using nix-instantiate
              nix-instantiate --eval --strict --json -E '
                let
                  data = import "'"$ROOT_DIR"'/secrets/identities.nix";
                  hosts = data.hostKeys;

                  extractRecipient = name: text:
                    let
                      lines = builtins.split "\n" text;
                      matching = builtins.filter (l: builtins.isString l && builtins.match ".*Recipient: age1.*" l != null) lines;
                    in
                    if matching != [] then
                      builtins.elemAt (builtins.match ".*Recipient: (age1[a-z0-9]+).*" (builtins.elemAt matching 0)) 0
                    else
                      null;

                  derivedIdentities = builtins.mapAttrs extractRecipient data.identities;
                in
                derivedIdentities // hosts
              ' > "$ROOT_DIR/scratch_recipients.json"

              cat <<'EOF' > "$RECIPIENTS_FILE"
              # Auto-generated by `nix run .#write-recipients` - DO NOT EDIT MANUALLY
              # Derived dynamically from secrets/identities.nix
              {
                recipients = {
              EOF

              ${pkgs.jq}/bin/jq -r 'to_entries[] | "    \(.key) = \"\(.value)\";"' "$ROOT_DIR/scratch_recipients.json" >> "$RECIPIENTS_FILE"
              rm -f "$ROOT_DIR/scratch_recipients.json"

              cat <<'EOF' >> "$RECIPIENTS_FILE"
                };
              }
              EOF
              echo "Wrote $RECIPIENTS_FILE cleanly."
            '';
          in
          "${script}/bin/write-recipients";
      };
    };

  flake.nixosModules.ragenix =
    { pkgs, ... }:
    let
      identitiesFile = pkgs.writeText "age-identities" identitiesText;
    in
    {
      imports = [ inputs.ragenix.nixosModules.default ];

      age.ageBin = "${pkgs.rage}/bin/rage";
      age.secretsDir = "/run/secrets";

      environment.systemPackages = secretPackages pkgs pkgs.stdenv.hostPlatform.system;

      # Automatically provision ~/.config/age/identities for all system users
      environment.etc."skel/.config/age/identities".source = identitiesFile;

      # Also ensure root / active default environment has the identity file deployed cleanly without heredocs
      system.activationScripts.deployAgeIdentities = {
        text = ''
          # Provision ~/.config/age/identities for all user home directories
          for udir in /home/*; do
            if [ -d "$udir" ]; then
              user="$(stat -c '%U:%G' "$udir")"
              mkdir -p "$udir/.config/age"
              cp -f ${identitiesFile} "$udir/.config/age/identities"
              chmod 0600 "$udir/.config/age/identities"
              chown -R "$user" "$udir/.config"
            fi
          done
        '';
      };

      age.secrets.hello-secret = {
        file = ../../secrets/encrypted/hello-secret.age;
        mode = "0444";
      };

      # Ensure pinentry can bind to the current TTY and define Fish wrappers for ragenix, rage, and pass
      environment.interactiveShellInit = ''
        export GPG_TTY=$(tty)
      '';
      programs.fish.interactiveShellInit = ''
        set -gx GPG_TTY (tty)

        # Force using only nano as editor, because e.g. VSC (code) may leak secrets to AI APIs.

        function pass --description 'pass wrapper ensuring nano is always used as editor'
            EDITOR=nano VISUAL=nano command pass $argv
        end

        function ragenix --description 'ragenix wrapper passing default ~/.config/age/identities and using nano editor'
            if test -f $HOME/.config/age/identities
                echo "(ragenix wrapper automatically using -f secrets/rules.nix -i $HOME/.config/age/identities)" >&2
                EDITOR=nano VISUAL=nano command ragenix -f secrets/rules.nix -i $HOME/.config/age/identities $argv
            else
                EDITOR=nano VISUAL=nano command ragenix -f secrets/rules.nix $argv
            end
        end

        function raged --description 'rage decryption helper passing default ~/.config/age/identities'
            if test -f $HOME/.config/age/identities
                command rage -d -i $HOME/.config/age/identities $argv
            else
                echo "raged: Error: identity file $HOME/.config/age/identities does not exist" >&2
                return 1
            end
        end
      '';
    };
}
