# https://nixbuild.net
# https://github.com/marketplace/actions/nixbuild-net
name: nixbuild.net
on: push
jobs:
  checks:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v24
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
